<a href="https://colab.research.google.com/github/exson6969/ml/blob/main/ML_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



*   Numpy is a python lib used for creating N-d arry. Which can be used to do algebra calculation.

## Numpy Arrays
 Methods to create numpy array
 * Transformation Standard list
 *  Build-in function
 * Generating random data


In [2]:
import numpy as np

my_list = [1,2,3]
print(type(my_list))

transformed_list = np.array(my_list)
print(type(transformed_list))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,10,13) # All output value between 0-10 are evenly spaced and produced 13 elements 

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [14]:
np.eye(5) # Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(4,6) #Create matrix of 4x6 all values between 0-1

array([[0.46857192, 0.98491459, 0.58175079, 0.2707617 , 0.80824897,
        0.19680889],
       [0.91175909, 0.531223  , 0.36390476, 0.21117605, 0.75922686,
        0.17059463],
       [0.92109151, 0.34968751, 0.59735052, 0.81339594, 0.94996813,
        0.24359457],
       [0.49702676, 0.14104735, 0.54884558, 0.14740403, 0.83556542,
        0.29279021]])

In [20]:
np.random.randn(6) # Standart normal distribution 

array([-0.26669984,  0.42298882, -0.92812707, -0.47287755, -0.23571877,
       -0.64533796])

In [24]:
np.random.randint(2,100, 45) # return random integers between 2-100

array([38,  6, 13, 10, 12, 51, 28, 70, 29, 67, 28, 21, 98, 71, 35, 27, 98,
        9, 47, 47, 81, 63, 59, 86, 18, 43, 18, 60, 47, 89, 48, 68,  2, 14,
       64, 44, 53, 51, 12, 31, 38, 79, 34, 24,  2])

In [27]:
np.random.seed(101)  # when these 2 commands are on same cell the output value will be ALWAYS same for given 101
np.random.rand(4) 

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [29]:
arr = np.arange(0,25)
print(arr)

arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr_copy = arr.copy()
arr_copy[:] = 0

print(arr)
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [34]:
bool_arr = arr > 10
print(bool_arr)

arr[bool_arr]

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr[arr > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])