In [2]:
import numpy as np

## Datatypes and Attributes

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12]]])

C:\Users\exson\AppData\Local\Temp\ipykernel_23804\4000183208.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12]]])


In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), list([[10, 11, 12]])],
      dtype=object)

In [7]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[7, 7, 9, 1, 4],
         [6, 9, 4, 2, 4],
         [1, 4, 6, 9, 9],
         [0, 7, 0, 4, 8]],

        [[2, 9, 2, 1, 9],
         [2, 9, 4, 3, 0],
         [4, 2, 5, 2, 3],
         [1, 7, 7, 3, 3]],

        [[7, 0, 8, 9, 7],
         [6, 4, 0, 8, 0],
         [8, 0, 3, 2, 9],
         [2, 2, 5, 0, 7]]],


       [[[9, 9, 7, 9, 2],
         [2, 5, 4, 9, 1],
         [4, 8, 3, 3, 6],
         [4, 8, 0, 1, 2]],

        [[5, 2, 3, 1, 7],
         [3, 2, 1, 0, 7],
         [9, 7, 1, 8, 9],
         [6, 1, 5, 0, 8]],

        [[6, 9, 8, 1, 6],
         [2, 7, 5, 6, 0],
         [2, 6, 5, 4, 6],
         [0, 0, 1, 2, 6]]]])

## Dot product

In [10]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (3,5))

np.dot(mat1, mat2)

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])